language: python
sudo: false

cache:
    pip: true
    directories:
        - $HOME/.cache/pip
        - $HOME/lua

env:
    - LUA="--lua 5.1"
    - LUA="--lua 5.2"
    - LUA="--lua 5.3"
    - LUA="--luajit 2.0"
    - LUA="--luajit 2.1"

install:
    - pip install hererocks
    - hererocks $HOME/lua --luarocks ^ $LUA
    - export PATH=$PATH:$HOME/lua/bin
    - luarocks install luacov
    - luarocks install luacov-coveralls

script:
    - luarocks make rockspecs/cparser-scm-1.rockspec
    - lua -lluacov test_cparser.lua

after_success:
    - luacov-coveralls -i '/cparser' -i '/cparser/*'
